version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "feat"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "develop"

  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "feat"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "develop"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3 