version: '3.8'

# Complete production-ready stack
# Run with: docker-compose -f docker-compose.full.yml up

services:
  # Include all services from previous phases
  # Application stack
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.yml  
      service: redis

  backend:
    extends:
      file: docker-compose.yml
      service: backend

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

  # Monitoring stack
  prometheus:
    extends:
      file: docker-compose.monitoring.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.monitoring.yml
      service: grafana

  cadvisor:
    extends:
      file: docker-compose.monitoring.yml
      service: cadvisor

# Add load balancer, backup services, etc.