apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://taskflow_prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://taskflow_loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false 